apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: bsis
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/component: observability
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "16"
    limits.memory: 24Gi
    persistentvolumeclaims: "15"
    requests.storage: 250Gi
    pods: "80"
    services: "30"
    configmaps: "200"
    secrets: "200"
