apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bsis-monitoring-integrations
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: bsis
  source:
    repoURL: https://github.com/HABTec/bsis-k8s.git
    targetRevision: main
    path: platform/monitoring-integrations
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
