apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bsis-app-development
  namespace: argocd
spec:
  project: bsis
  source:
    repoURL: https://github.com/HABTec/bsis-k8s.git
    targetRevision: main
    path: apps/overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: app-development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
