apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bsis-app-stage
  namespace: argocd
spec:
  project: bsis
  source:
    repoURL: https://github.com/HABTec/bsis-k8s.git
    targetRevision: main
    path: apps/overlays/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: app-stage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
