apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bsis-cert-manager-issuers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: bsis
  source:
    repoURL: https://github.com/HABTec/bsis-k8s.git
    targetRevision: main
    path: platform/cert-manager-config
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
