apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bsis-app
  labels:
    app.kubernetes.io/name: bsis-app
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: bsis
    app.kubernetes.io/managed-by: argocd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bsis-app
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
