apiVersion: v1
kind: ServiceAccount
metadata:
  name: bsis-app
  labels:
    app.kubernetes.io/name: bsis-app
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: bsis
    app.kubernetes.io/managed-by: argocd
